export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILES = 'GET_PROFILES';
export const USER_ORDERS_LOADING = 'USER_ORDERS_LOADING';
export const USER_ORDERS = 'USER_ORDERS';
export const SINGLE_ORDER = 'SINGLE_ORDER';
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';